name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: EditorConfig Lint
        uses: docker://mstruebing/editorconfig-checker:v3.6.1

      - name: Enable corepack
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Check JSR publishing
        run: yarn publish:jsr --dry-run

      - name: Test
        run: |
          yarn coverage > COVERAGE_RESULT
          echo "$(cat COVERAGE_RESULT)"

  release:
    name: Release
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'mikro-orm'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: apify/workflows/execute-workflow@main
        with:
          workflow: release.yml
          inputs: >
            {
              "ref": "${{ steps.commit.outputs.commit_long_sha || github.sha }}",
              "dist-tag": "next"
            }
